import type {AppLanguage} from "@/src/i18n/types";
import type {RecommendationMethodologyId} from "@/src/lib/recommendation-engine";

export interface RecommendationCategoryChartDatum{key:string;label:string;shortLabel:string;current:number|null;constrained:number|null;recommended:number|null}
const labels={
  the:{teaching:{tr:["Öğretim","Öğretim"],en:["Teaching","Teaching"]},researchEnvironment:{tr:["Araştırma Ortamı","Araştırma Ort."],en:["Research Environment","Research Env."]},researchQuality:{tr:["Araştırma Kalitesi","Araştırma Kal."],en:["Research Quality","Research Quality"]},industry:{tr:["Endüstri","Endüstri"],en:["Industry","Industry"]},internationalOutlook:{tr:["Uluslararası Görünüm","Uluslararası"],en:["International Outlook","International"]}},
  qs:{researchDiscovery:{tr:["Araştırma","Araştırma"],en:["Research","Research"]},employabilityOutcomes:{tr:["İstihdam","İstihdam"],en:["Employability","Employability"]},globalEngagement:{tr:["Küresel Katılım","Küresel Katılım"],en:["Global Engagement","Global Engagement"]},learningExperience:{tr:["Öğrenme","Öğrenme"],en:["Learning","Learning"]},sustainability:{tr:["Sürdürülebilirlik","Sürdürülebilirlik"],en:["Sustainability","Sustainability"]}},
  "ui-greenmetric":{SI:{tr:["Yapı ve Altyapı","Altyapı"],en:["Setting and Infrastructure","Infrastructure"]},EC:{tr:["Enerji ve İklim Değişikliği","Enerji"],en:["Energy and Climate Change","Energy"]},WS:{tr:["Atık","Atık"],en:["Waste","Waste"]},WR:{tr:["Su","Su"],en:["Water","Water"]},TR:{tr:["Ulaşım","Ulaşım"],en:["Transportation","Transportation"]},ED:{tr:["Eğitim ve Araştırma","Eğitim"],en:["Education and Research","Education"]},GD:{tr:["Yönetişim ve Dijitalleşme","Yönetişim"],en:["Governance and Digitalization","Governance"]}}
} as const;
export function getRecommendationCategoryLabel(methodology:RecommendationMethodologyId,key:string,language:AppLanguage){const entry=(labels[methodology] as Record<string,{tr:readonly[string,string];en:readonly[string,string]}>)[key]?.[language];return entry?{label:entry[0],shortLabel:entry[1]}:{label:key,shortLabel:key}}
export function createRecommendationCategoryChartData({methodology,current,constrained=current,recommended,language}:{methodology:RecommendationMethodologyId;current:Record<string,number|null>;constrained?:Record<string,number|null>;recommended:Record<string,number|null>;language:AppLanguage}):RecommendationCategoryChartDatum[]{return Object.keys(recommended).map(key=>{const translated=getRecommendationCategoryLabel(methodology,key,language);return{key,...translated,current:current[key]??null,constrained:constrained[key]??null,recommended:recommended[key]??null}})}
