import { parseStoredInstitutionData,type StoredInstitutionData } from "@/src/contexts/InstitutionDataContext";
import { parseSavedScenarioState,SAVED_SCENARIOS_STORAGE_KEY,type SavedScenarioState } from "@/src/lib/scenarios/saved-scenario-store";
import { APPLICATION_SETTINGS_STORAGE_KEY,DEFAULT_APPLICATION_SETTINGS,parseApplicationSettings,type ApplicationSettings } from "./settings-store";
import { getActiveRankingDatasetKeys } from "@/src/lib/rankings/dataset-storage";

export const LOCAL_DATA_KEYS={institutional:"uni-predictor:institution-data",baseline:"uni-predictor:baseline-overrides",scenarios:SAVED_SCENARIOS_STORAGE_KEY,recommendationDrafts:"uni-predictor:recommendation-drafts",scenarioDrafts:"uni-predictor:scenario-changes",settings:APPLICATION_SETTINGS_STORAGE_KEY,language:"uni-predictor:language"} as const;
export type LocalBackup={schemaVersion:1;exportedAt:string;applicationVersion:string;institutionalData:StoredInstitutionData|null;scenarios:SavedScenarioState;recommendationDrafts:unknown;applicationPreferences:{settings:ApplicationSettings;language:"tr"|"en"};activeReferenceDatasetSelections:ReturnType<typeof getActiveRankingDatasetKeys>};
const read=(key:string)=>typeof window==="undefined"?null:localStorage.getItem(key);
export function createLocalBackup(applicationVersion:string):LocalBackup{return{schemaVersion:1,exportedAt:new Date().toISOString(),applicationVersion,institutionalData:parseStoredInstitutionData(read(LOCAL_DATA_KEYS.institutional)),scenarios:parseSavedScenarioState(read(LOCAL_DATA_KEYS.scenarios)),recommendationDrafts:parseJson(read(LOCAL_DATA_KEYS.recommendationDrafts)),applicationPreferences:{settings:parseApplicationSettings(read(LOCAL_DATA_KEYS.settings)),language:read(LOCAL_DATA_KEYS.language)==="en"?"en":"tr"},activeReferenceDatasetSelections:getActiveRankingDatasetKeys()};}
const parseJson=(raw:string|null)=>{if(!raw)return null;try{return JSON.parse(raw) as unknown;}catch{return null;}};
export function parseLocalBackup(raw:string):{backup:LocalBackup|null;errors:string[];warnings:string[]}{try{const value=JSON.parse(raw) as Partial<LocalBackup>;if(value.schemaVersion!==1)return{backup:null,errors:["unsupported-schema"],warnings:[]};if(!value.scenarios||!value.applicationPreferences)return{backup:null,errors:["invalid-backup"],warnings:[]};return{backup:value as LocalBackup,errors:[],warnings:[]};}catch{return{backup:null,errors:["invalid-json"],warnings:[]};}}
export function applyLocalBackup(backup:LocalBackup,mode:"merge"|"overwrite"){
  if(typeof window==="undefined")return;
  const existingScenarios=parseSavedScenarioState(read(LOCAL_DATA_KEYS.scenarios));
  const scenarios=mode==="overwrite"?backup.scenarios.scenarios:mergeScenarios(existingScenarios.scenarios,backup.scenarios.scenarios);
  if(backup.institutionalData){if(mode==="overwrite")localStorage.setItem(LOCAL_DATA_KEYS.institutional,JSON.stringify(backup.institutionalData));else{const current=parseStoredInstitutionData(read(LOCAL_DATA_KEYS.institutional));localStorage.setItem(LOCAL_DATA_KEYS.institutional,JSON.stringify(current?{...current,updatedAt:new Date().toISOString(),activeYears:{...current.activeYears,...backup.institutionalData.activeYears},data:{the:{...backup.institutionalData.data.the,...current.data.the},qs:{...backup.institutionalData.data.qs,...current.data.qs},uiGreenMetric:{...backup.institutionalData.data.uiGreenMetric,...current.data.uiGreenMetric}}}:backup.institutionalData));}}
  localStorage.setItem(LOCAL_DATA_KEYS.scenarios,JSON.stringify({version:1,scenarios}));
  localStorage.setItem(LOCAL_DATA_KEYS.settings,JSON.stringify(backup.applicationPreferences.settings??DEFAULT_APPLICATION_SETTINGS));localStorage.setItem(LOCAL_DATA_KEYS.language,backup.applicationPreferences.language);
  if(backup.recommendationDrafts!==null)localStorage.setItem(LOCAL_DATA_KEYS.recommendationDrafts,JSON.stringify(backup.recommendationDrafts));
}
export function mergeScenarios(current:SavedScenarioState["scenarios"],incoming:SavedScenarioState["scenarios"]){const map=new Map(current.map(item=>[item.id,item]));for(const item of incoming){const existing=map.get(item.id);if(!existing||Date.parse(item.updatedAt)>=Date.parse(existing.updatedAt))map.set(item.id,item);}return[...map.values()];}
export function getLocalDataSummary(){const institutional=parseStoredInstitutionData(read(LOCAL_DATA_KEYS.institutional));const scenarios=parseSavedScenarioState(read(LOCAL_DATA_KEYS.scenarios));return{institutionalCount:institutional?Object.keys(institutional.data.the).length+Object.keys(institutional.data.qs).length+Object.keys(institutional.data.uiGreenMetric).length:0,scenarioCount:scenarios.scenarios.length,recommendationDraftCount:countValue(parseJson(read(LOCAL_DATA_KEYS.recommendationDrafts))),preferenceCount:read(LOCAL_DATA_KEYS.settings)?1:0,institutionalUpdatedAt:institutional?.updatedAt||null,scenarioUpdatedAt:scenarios.scenarios.map(item=>item.updatedAt).sort().at(-1)??null};}
const countValue=(value:unknown)=>Array.isArray(value)?value.length:value&&typeof value==="object"?Object.keys(value).length:0;
export function clearLocalDataGroup(group:"institutional"|"scenarios"|"recommendationDrafts"|"preferences"){if(typeof window==="undefined")return;const keys=group==="institutional"?[LOCAL_DATA_KEYS.institutional,LOCAL_DATA_KEYS.baseline]:group==="scenarios"?[LOCAL_DATA_KEYS.scenarios]:group==="recommendationDrafts"?[LOCAL_DATA_KEYS.recommendationDrafts]:[LOCAL_DATA_KEYS.settings];keys.forEach(key=>localStorage.removeItem(key));}
export function clearAllLocalStorageGroups(){if(typeof window==="undefined")return;Object.values(LOCAL_DATA_KEYS).forEach(key=>localStorage.removeItem(key));}
