const qsUiTranslationsBase = {
  tr: {
    inputTitle:"QS Girdi Parametreleri", dataYear:"Veri yılı", validationBlocked:"Parametre hataları düzeltilmeden simülasyon güncellenemez.", dataReference:"Kurumsal veri yılı: {year} · QS skor referansı: {edition} · Sonuçlar tahmini what-if simülasyonudur.", updating:"Simülasyon güncelleniyor…",
    currentValue:"Mevcut", aggregateTotalHelp:"Toplam kişi sayısıdır; mevcut FT/PT dağılımı korunur.", employmentHelp:"Alt değerler ilgili üst toplamları aşamaz. Boş bırakılan alanlarda kurumsal mevcut değer kullanılır.", surveyResponseRate:"Anket yanıt oranı", graduateEmploymentRate:"Ham mezun istihdam oranı", eoScoreImpact:"EO sayısal skor etkisi", couldNotCalculate:"Hesaplanamadı", lensChart:"QS Gösterge Dağılımı", lensChartDescription:"Mevcut ve senaryo QS gösterge skorlarının radar görünümü", lensChartAria:"QS radar grafiği: mevcut ve senaryo gösterge skorlarını karşılaştırır", scoreChart:"QS Puan Karşılaştırması", scoreChartDescription:"Mevcut ve senaryo gösterge puanlarının karşılaştırması", scoreChartAria:"QS sütun grafiği: mevcut ve senaryo gösterge skorlarını karşılaştırır", chartPreparing:"Grafik verileri hazırlanıyor…", chartInsufficient:"Grafik için yeterli QS gösterge skoru bulunmuyor.", chartUpdating:"Güncelleniyor…", missingLenses:"Bazı lensler gerekli gösterge skorları eksik olduğu için gösterilemedi.", missingIndicators:"Bazı göstergeler gerekli veri veya kalibrasyon bulunmadığı için gösterilemedi.", current:"Mevcut", scenario:"Senaryo", difference:"Fark", weight:"Ağırlık",
    currentEstimated:"Mevcut Tahmini Skor", scenarioEstimated:"Senaryo Tahmini Skoru", scoreChange:"Skor Değişimi", estimatedBand:"Tahmini Sıralama Bandı", calculationStatus:"Hesaplama Durumu", currentEstimateDescription:"QS 2027 gösterge sonuçlarından üretilen ampirik overall tahmini.", scenarioEstimateDescription:"Senaryo gösterge sonuçlarının tahmini overall karşılığı.", waitingIndicators:"Gerekli gösterge verileri bekleniyor.", scoreDifferenceDescription:"Mevcut ve senaryo tahmini skor farkı.", rankDescription:"Kayıtlı QS referans verisine dayalı tahmini bant.", rankMissing:"Sıralama tahmini için tüm ağırlıklı gösterge skorları gerekli", parameterError:"Parametre hatası", rawAnalysis:"Yalnız ham etki", complete:"Tamamlandı", missingData:"Eksik veri", heldScores:"Ham oran değişti; gösterge skoru için yeterli kalibrasyon verisi bulunmuyor.", calculated:"Senaryo sonuçları başarıyla hesaplandı.", ready:"Hazır: {ready} / {total}", validationDetail:"Parametrelerdeki tutarsızlıklar giderilmeden senaryo sonucu tamamlanamaz.", readyDetail:"Hesaplamaya hazır ağırlıklı gösterge sayısı: {ready} / {total}.", rawDetail:"Ham kurumsal değerler ve oranlar değişti. Yeterli eşlenmiş QS raw-to-score kalibrasyonu bulunmadığı için senaryo gösterge skoru, genel skor farkı ve sıralama üretilmedi.", completeDetail:"Kurumsal veri {year} ve QS {edition} referanslarıyla what-if hesaplaması tamamlandı.", technicalDetails:"Teknik Hesaplama Ayrıntıları", composite:"Ağırlıklı Gösterge Bileşimi", currentComposite:"Mevcut ağırlıklı bileşim", scenarioComposite:"Senaryo ağırlıklı bileşim", compositeDifference:"Bileşim farkı", compositeDescription:"Dokuz QS gösterge skorunun resmî ağırlıklarıyla oluşturulan teknik bileşimdir. Kamuya açık gösterge skorları yuvarlanmış olduğundan resmî overall skorla birebir eşleşmeyebilir. Tahmini QS genel skorunun ampirik normalizer ile hesaplanmasında ara değer olarak kullanılır.",
  },
  en: {
    inputTitle:"QS Input Parameters", dataYear:"Data year", validationBlocked:"The simulation cannot update until parameter errors are corrected.", dataReference:"Institutional data year: {year} · QS score reference: {edition} · Results are an estimated what-if simulation.", updating:"Updating simulation…",
    currentValue:"Current", aggregateTotalHelp:"This is the total headcount; the current FT/PT distribution is preserved.", employmentHelp:"Sub-values cannot exceed their related totals. Empty fields keep the current institutional value.", surveyResponseRate:"Survey response rate", graduateEmploymentRate:"Raw graduate employment rate", eoScoreImpact:"EO numeric score impact", couldNotCalculate:"Could not be calculated", lensChart:"QS Indicator Distribution", lensChartDescription:"Radar view of current and scenario QS indicator scores", lensChartAria:"QS radar chart comparing current and scenario indicator scores", scoreChart:"QS Score Comparison", scoreChartDescription:"Comparison of current and scenario indicator scores", scoreChartAria:"QS bar chart comparing current and scenario indicator scores", chartPreparing:"Preparing chart data…", chartInsufficient:"There are not enough QS indicator scores for the chart.", chartUpdating:"Updating…", missingLenses:"Some lenses could not be shown because required indicator scores are missing.", missingIndicators:"Some indicators could not be shown because required data or calibration is unavailable.", current:"Current", scenario:"Scenario", difference:"Difference", weight:"Weight",
    currentEstimated:"Current Estimated Score", scenarioEstimated:"Scenario Estimated Score", scoreChange:"Score Change", estimatedBand:"Estimated Ranking Band", calculationStatus:"Calculation Status", currentEstimateDescription:"Empirical overall estimate based on QS 2027 indicator results.", scenarioEstimateDescription:"Estimated overall equivalent of the scenario indicator results.", waitingIndicators:"Required indicator data is pending.", scoreDifferenceDescription:"Difference between current and scenario estimated scores.", rankDescription:"Estimated band based on stored QS reference data.", rankMissing:"All weighted indicator scores are required for the ranking estimate", parameterError:"Parameter error", rawAnalysis:"Raw impact only", complete:"Complete", missingData:"Missing data", heldScores:"The raw ratio changed; sufficient indicator-score calibration data is unavailable.", calculated:"Scenario results were calculated successfully.", ready:"Ready: {ready} / {total}", validationDetail:"The scenario result cannot be completed until parameter inconsistencies are corrected.", readyDetail:"Weighted indicators ready for calculation: {ready} / {total}.", rawDetail:"Raw institutional values and ratios changed. Because sufficient paired QS raw-to-score calibration is unavailable, no scenario indicator score, overall delta, or rank was produced.", completeDetail:"The what-if calculation was completed using institutional data {year} and QS {edition} references.", technicalDetails:"Technical Calculation Details", composite:"Weighted Indicator Composite", currentComposite:"Current weighted composite", scenarioComposite:"Scenario weighted composite", compositeDifference:"Composite difference", compositeDescription:"This technical composite is formed from the nine QS indicator scores using their official weights. Public indicator scores are rounded, so it may not exactly match the official overall score. It is used as an intermediate value when calculating the estimated QS overall score with the empirical normalizer.",
  },
} as const;

export const qsUiTranslations = {
  tr: {
    ...qsUiTranslationsBase.tr,
    rawAnalysis: "Yalnız ham etki",
    calibrationUnavailable: "Ham oran değişti; gösterge skoru için yeterli kalibrasyon verisi bulunmuyor.",
    heldScores: "Ham oran değişti; gösterge skoru için yeterli kalibrasyon verisi bulunmuyor.",
    rawDetail: "Ham kurumsal değerler ve oranlar değişti. Yeterli eşlenmiş QS raw-to-score kalibrasyonu bulunmadığı için senaryo gösterge skoru, genel skor farkı ve sıralama üretilmedi.",
  },
  en: {
    ...qsUiTranslationsBase.en,
    rawAnalysis: "Raw impact only",
    calibrationUnavailable: "The raw ratio changed; sufficient calibration data is unavailable for the indicator score.",
    heldScores: "The raw ratio changed; sufficient calibration data is unavailable for the indicator score.",
    rawDetail: "Raw institutional values and ratios changed. Because sufficient paired QS raw-to-score calibration is unavailable, no scenario indicator score, overall delta, or rank was produced.",
  },
} as const;
