const sharedTr = {
  rankBands: "Sıralama Bantları", officialCurrentBandDetail: "THE 2026 yayımlanmış referans bandı", estimatedScenarioBandDetail: "Senaryo sonuçlarından tahmin edilmiştir", sameOfficialBandDetail: "Mevcut resmî referans bandıyla aynı",
  insufficientCoverageStatus: "Referans kapsamı yetersiz", insufficientCoverageDetail: "Yeterli karşılaştırılabilir THE referans kaydı bulunmadığından güvenilir bir senaryo sıralama bandı üretilemedi.",
  compactMethodDescription: "THE 2026 ağırlıklarıyla {count} denemeli stokastik simülasyon.",
  scoreComparison: "Puan Karşılaştırması",
  currentScore: "THE Mevcut Skoru", scenarioScore: "THE Senaryo Skoru", stochasticEstimate: "Stokastik THE tahmini", change: "Değişim", medianDifference: "Medyan skor farkı", estimatedRankBand: "Tahmini Sıralama Bandı", referenceDistribution: "THE 2026 referans dağılımı", calculationStatus: "Hesaplama Durumu", updating: "Simülasyon güncelleniyor…", complete: "Stokastik simülasyon tamamlandı", incomplete: "Simülasyon tamamlanamadı", runsModel: "{count} deneme • THE 2026 modeli",
  resultsTable: "THE Sonuç Tablosu", resultsDescription: "Mevcut durum ve senaryo sonuçlarının karşılaştırması", invalidInputs: "Bazı zorunlu gösterge girdileri geçersiz veya eksik.", calculationMethod: "Hesaplama Yöntemi", methodDescription: "Kurumsal girdiler ve resmî THE gösterge ağırlıkları kullanılarak {count} denemeli stokastik simülasyon yapılmıştır.", methodDetails: "Yöntem ayrıntıları", modelType: "Model türü", stochastic: "Stokastik", runCount: "Deneme sayısı", modelVersion: "Model sürümü", institutionalYear: "Kurumsal veri yılı", calibrationYear: "Kalibrasyon yılı", referenceInstitutions: "Referans kurum", seed: "Seed", stochasticIndicators: "Kesin gösterge", modelInputsUsed: "Model girdisi kullanılan",
  categoryDistribution: "Kategori Dağılımı", categoryDistributionDescription: "Mevcut ve senaryo THE kategori skorlarının radar görünümü", categoryDistributionAria: "Mevcut ve senaryo THE kategori skorlarını gösteren radar grafik", scoreChange: "Puan Değişimi", scoreChangeDescription: "Mevcut ve senaryo kategori puanlarının karşılaştırması", scoreChangeAria: "Mevcut ve senaryo THE kategori skorlarını karşılaştıran sütun grafik", chartNotReady: "Grafik verisi henüz hazır değil", chartNotReadyDescription: "Kategori skorlarının tamamlanması için normalizasyon referansları ve gerekli girişler bekleniyor.",
  changedMetrics: "Değiştirilen Metrikler", noChangedMetrics: "Henüz değiştirilmiş bir THE metriği bulunmuyor.", metric: "Metrik", currentValue: "Mevcut Değer", scenarioValue: "Senaryo Değeri", informationalOnly: "Bilgi amaçlı – THE puanını etkilemez", reflectedChanges: "Hesaplamaya yansıyan", unreflectedChanges: "Skora yansıtılamayan", scoreImpactUnavailable: "Senaryo skorunu etkilemez", scoreImpactUnavailableDetail: "Senaryo skorunu etkilemez – doğrulanmış ham→skor dönüşümü bulunmuyor.", showLess: "Daha az göster", showAllChanges: "Tüm değişiklikleri göster", showDetails: "Ayrıntılı Göster",
  indicator: "Gösterge", current: "Mevcut", scenario: "Senaryo", difference: "Fark", overallScore: "Genel THE Skoru", teaching: "Öğretim", researchEnvironment: "Araştırma Ortamı", researchQuality: "Araştırma Kalitesi", internationalOutlook: "Uluslararası Görünüm", industry: "Sanayi",
} as const;

export const theUiTranslations = {
  tr: sharedTr,
  en: {
    rankBands: "Ranking Bands", officialCurrentBandDetail: "Published THE 2026 reference band", estimatedScenarioBandDetail: "Estimated from the scenario results", sameOfficialBandDetail: "Same as the current official reference band",
    insufficientCoverageStatus: "Insufficient reference coverage", insufficientCoverageDetail: "A reliable scenario ranking band could not be produced because there are not enough comparable THE reference records.",
    compactMethodDescription: "{count}-run stochastic simulation with THE 2026 weights.",
    scoreComparison: "Score Comparison",
    currentScore: "Current THE Score", scenarioScore: "Scenario THE Score", stochasticEstimate: "Stochastic THE estimate", change: "Change", medianDifference: "Median score difference", estimatedRankBand: "Estimated Ranking Band", referenceDistribution: "THE 2026 reference distribution", calculationStatus: "Calculation Status", updating: "Updating simulation…", complete: "Stochastic simulation complete", incomplete: "Simulation could not be completed", runsModel: "{count} runs • THE 2026 model",
    resultsTable: "THE Results Table", resultsDescription: "Comparison of current and scenario results", invalidInputs: "Some required indicator inputs are invalid or missing.", calculationMethod: "Calculation Method", methodDescription: "A {count}-run stochastic simulation was performed using institutional inputs and official THE indicator weights.", methodDetails: "Method details", modelType: "Model type", stochastic: "Stochastic", runCount: "Run count", modelVersion: "Model version", institutionalYear: "Institutional data year", calibrationYear: "Calibration year", referenceInstitutions: "Reference institutions", seed: "Seed", stochasticIndicators: "Stochastic indicators", modelInputsUsed: "Unavailable indicators",
    categoryDistribution: "Category Distribution", categoryDistributionDescription: "Radar view of current and scenario THE category scores", categoryDistributionAria: "Radar chart showing current and scenario THE category scores", scoreChange: "Score Change", scoreChangeDescription: "Comparison of current and scenario category scores", scoreChangeAria: "Bar chart comparing current and scenario THE category scores", chartNotReady: "Chart data is not ready yet", chartNotReadyDescription: "Normalization references and required inputs are needed to complete the category scores.",
    changedMetrics: "Changed Metrics", noChangedMetrics: "No THE metrics have been changed yet.", metric: "Metric", currentValue: "Current Value", scenarioValue: "Scenario Value", informationalOnly: "Informational only – does not affect the THE score", reflectedChanges: "Reflected in calculation", unreflectedChanges: "Not reflected in score", scoreImpactUnavailable: "Does not affect scenario score", scoreImpactUnavailableDetail: "Does not affect the scenario score – no verified raw-to-score conversion is available.", showLess: "Show less", showAllChanges: "Show all changes", showDetails: "Show Details",
    indicator: "Indicator", current: "Current", scenario: "Scenario", difference: "Difference", overallScore: "Overall THE Score", teaching: "Teaching", researchEnvironment: "Research Environment", researchQuality: "Research Quality", internationalOutlook: "International Outlook", industry: "Industry",
  },
} as const;
