import type { GreenMetricValue, GreenMetricValues } from "@/src/types/greenmetric";
import type { UiGreenMetricCategoryCode, UiGreenMetricIndicatorCode, UiGreenMetricIndicatorResult } from "./types";
import { calculateDerivedValue, getGreenMetricRelationWarningsForMetrics, GREEN_METRIC_POPULATION_METRIC_IDS, GREEN_METRIC_RENEWABLE_PRODUCTION_IDS } from "@/src/utils/greenmetric-derived";

export function safeDivide(n:number|null|undefined,d:number|null|undefined){return n==null||d==null||!Number.isFinite(n)||!Number.isFinite(d)||d<=0?null:n/d}
export const nearlyEqual=(a:number,b:number,e=1e-9)=>Math.abs(a-b)<=e;
const num=(v:GreenMetricValue)=>typeof v==="number"&&Number.isFinite(v)?v:null;
const n=(v:GreenMetricValues,id:string)=>num(v[id]);
const level=(v:GreenMetricValues,id:string)=>{const x=v[id];if(typeof x!=="string"||x==="")return null;const parsed=Number(x);return Number.isInteger(parsed)?parsed:null};
const result=(code:UiGreenMetricIndicatorCode,max:number,raw:GreenMetricValue,score:number|null,ids:string[],manual=false,validationWarnings:string[]=[]):UiGreenMetricIndicatorResult=>({code,category:code.slice(0,2) as UiGreenMetricCategoryCode,rawValue:raw,score,maximumScore:max,status:manual?"manual-review":validationWarnings.length?"invalid-input":raw==null?"missing-input":typeof raw==="number"&&!Number.isFinite(raw)?"invalid-input":score==null?"invalid-input":"scored",sourceMetricIds:ids,warnings:manual?["Resmî kılavuzdaki sınır tanımı bu değer için açık değildir."]:validationWarnings});
const bands=(x:number|null,values:[(x:number)=>boolean,number][])=>x==null?null:values.find(([p])=>p(x))?.[1]??null;
const lv=(v:GreenMetricValues,code:UiGreenMetricIndicatorCode,id:string,max:number,scores:number[])=>{const x=level(v,id);return result(code,max,x,x==null?null:scores[x-1]??null,[id])};
const count=(v:GreenMetricValues,code:UiGreenMetricIndicatorCode,id:string,max:number,cuts:number[],scores:number[])=>{const x=n(v,id);return result(code,max,x,x==null||x<0?null:scores[cuts.findIndex(c=>x<=c)]??scores.at(-1)!,[id])};
const derivedResult=(v:GreenMetricValues,code:UiGreenMetricIndicatorCode,derivedId:string,max:number,ids:string[],scoreBands:[(x:number)=>boolean,number][])=>{const x=calculateDerivedValue(derivedId,v),warnings=getGreenMetricRelationWarningsForMetrics(v,ids);return result(code,max,x,bands(x,scoreBands),ids,false,warnings)};

export function calculateSI1(v:GreenMetricValues){const ids=["greenmetric.common.totalCampusAreaM2","greenmetric.common.buildingGroundFloorAreaM2"];return derivedResult(v,"SI1","greenmetric.derived.openSpaceRatio",200,ids,[[x=>x<=1,10],[x=>x<=80,50],[x=>x<=90,100],[x=>x<=95,150],[()=>true,200]])}
export function calculateSI2(v:GreenMetricValues){const ids=["greenmetric.si.forestVegetationAreaM2","greenmetric.common.totalCampusAreaM2"];return derivedResult(v,"SI2","greenmetric.derived.forestVegetationRatio",100,ids,[[x=>x<=2,5],[x=>x<=10,25],[x=>x<=25,50],[x=>x<=35,75],[()=>true,100]])}
export function calculateSI3(v:GreenMetricValues){const ids=["greenmetric.si.plantedVegetationAreaM2","greenmetric.common.totalCampusAreaM2"];return derivedResult(v,"SI3","greenmetric.derived.plantedVegetationRatio",200,ids,[[x=>x<=10,10],[x=>x<=20,50],[x=>x<=30,100],[x=>x<=50,150],[()=>true,200]])}
export function calculateSI4(v:GreenMetricValues){const ids=["greenmetric.common.totalCampusAreaM2","greenmetric.common.buildingGroundFloorAreaM2",...GREEN_METRIC_POPULATION_METRIC_IDS];return derivedResult(v,"SI4","greenmetric.derived.openSpacePerPerson",200,ids,[[x=>x<=10,10],[x=>x<=20,50],[x=>x<=40,100],[x=>x<=70,150],[()=>true,200]])}
export const calculateSI5=(v:GreenMetricValues)=>lv(v,"SI5","greenmetric.si.accessibilityFacilitiesLevel",100,[0,25,50,75,100]);
export const calculateSI6=(v:GreenMetricValues)=>lv(v,"SI6","greenmetric.si.securitySafetyLevel",100,[0,25,50,75,100]);
export const calculateSI7=(v:GreenMetricValues)=>lv(v,"SI7","greenmetric.si.healthInfrastructureLevel",100,[0,25,50,75,100]);
export const calculateSI8=(v:GreenMetricValues)=>lv(v,"SI8","greenmetric.si.conservationProgramLevel",100,[5,25,50,75,100]);
export function calculateEC1(v:GreenMetricValues){return percent(v,"EC1","greenmetric.ec.energyEfficientApplianceRatio",200,[[x=>x<1,10],[x=>x<=25,50],[x=>x<=50,100],[x=>x<=75,150],[()=>true,200]])}
export function calculateEC2(v:GreenMetricValues){const ids=["greenmetric.ec.smartBuildingAreaM2","greenmetric.common.totalBuildingFloorAreaM2"];return derivedResult(v,"EC2","greenmetric.derived.smartBuildingRatio",300,ids,[[x=>x<1,15],[x=>x<=25,75],[x=>x<=50,150],[x=>x<=75,225],[()=>true,300]])}
export function calculateEC3(v:GreenMetricValues){const id="greenmetric.ec.renewableEnergySources",x=Array.isArray(v[id])?v[id].length:null;return result("EC3",300,x,x==null?null:x===0?0:x===1?75:x===2?150:x===3?225:300,[id])}
export function calculateEC4(v:GreenMetricValues){const ids=["greenmetric.common.totalAnnualElectricityKwh",...GREEN_METRIC_POPULATION_METRIC_IDS],x=calculateDerivedValue("greenmetric.derived.electricityPerPerson",v),manual=x!=null&&nearlyEqual(x,600);return result("EC4",200,x,manual?null:bands(x,[[x=>x>=2400,10],[x=>x>1500,50],[x=>x>600,100],[x=>x>=250,150],[()=>true,200]]),ids,manual)}
export function calculateEC5(v:GreenMetricValues){const ids=["greenmetric.common.totalAnnualEnergyUsageKwh",...GREEN_METRIC_RENEWABLE_PRODUCTION_IDS];return derivedResult(v,"EC5","greenmetric.derived.renewableEnergyRatio",200,ids,[[x=>x<=.5,10],[x=>x<=1,50],[x=>x<=2,100],[x=>x<=25,150],[()=>true,200]])}
export const calculateEC6=(v:GreenMetricValues)=>count(v,"EC6","greenmetric.ec.greenBuildingElementCount",200,[0,1,2,3],[0,50,100,150,200]);
export const calculateEC7=(v:GreenMetricValues)=>lv(v,"EC7","greenmetric.ec.ghgReductionProgramLevel",200,[0,50,100,150,200]);
export function calculateEC8(v:GreenMetricValues){const ids=["greenmetric.common.totalCarbonFootprintTons",...GREEN_METRIC_POPULATION_METRIC_IDS],x=calculateDerivedValue("greenmetric.derived.carbonFootprintPerPerson",v),manual=x!=null&&nearlyEqual(x,.1);return result("EC8",200,x,manual?null:bands(x,[[x=>x>=2.05,10],[x=>x>1.11,50],[x=>x>.42,100],[x=>x>.1,150],[()=>true,200]]),ids,manual)}
export const calculateEC9=(v:GreenMetricValues)=>count(v,"EC9","greenmetric.ec.innovativeProgramCount",100,[0,1,2,3],[0,25,50,75,100]);
export const calculateEC10=(v:GreenMetricValues)=>lv(v,"EC10","greenmetric.ec.climateImpactProgramLevel",100,[0,25,50,75,100]);
const percent=(v:GreenMetricValues,code:UiGreenMetricIndicatorCode,id:string,max:number,bs:[(x:number)=>boolean,number][])=>{const x=n(v,id);return result(code,max,x,bands(x,bs),[id])};
export const calculateWS1=(v:GreenMetricValues)=>lv(v,"WS1","greenmetric.ws.threeRProgramLevel",200,[0,50,100,150,200]);
export const calculateWS2=(v:GreenMetricValues)=>count(v,"WS2","greenmetric.ws.paperPlasticReductionProgramCount",300,[0,3,6,10],[0,75,150,225,300]);
const waste=(v:GreenMetricValues,code:"WS3"|"WS4"|"WS5",prefix:string)=>{const ids=[`greenmetric.ws.${prefix}WasteTreatedCurrentTons`,`greenmetric.ws.${prefix}WasteProducedCurrentTons`];return derivedResult(v,code,`greenmetric.derived.${prefix}WasteTreatmentRatio`,300,ids,[[x=>x<=0,0],[x=>x<=35,75],[x=>x<=65,150],[x=>x<=85,225],[()=>true,300]])};
export const calculateWS3=(v:GreenMetricValues)=>waste(v,"WS3","organic");export const calculateWS4=(v:GreenMetricValues)=>waste(v,"WS4","inorganic");export const calculateWS5=(v:GreenMetricValues)=>waste(v,"WS5","toxic");
export const calculateWS6=(v:GreenMetricValues)=>lv(v,"WS6","greenmetric.ws.sewageTreatmentLevel",300,[0,75,150,225,300]);
export function calculateWR1(v:GreenMetricValues){const ids=["greenmetric.wr.waterAbsorptionAreaM2","greenmetric.common.totalCampusAreaM2"];return derivedResult(v,"WR1","greenmetric.derived.waterAbsorptionRatio",100,ids,[[x=>x<=2,5],[x=>x<=10,25],[x=>x<=20,50],[x=>x<=40,75],[()=>true,100]])}
export const calculateWR2=(v:GreenMetricValues)=>lv(v,"WR2","greenmetric.wr.waterConservationLevel",200,[0,50,100,150,200]);export const calculateWR3=(v:GreenMetricValues)=>lv(v,"WR3","greenmetric.wr.waterRecyclingLevel",200,[0,50,100,150,200]);
export function calculateWR4(v:GreenMetricValues){return percent(v,"WR4","greenmetric.wr.waterEfficientApplianceRatio",200,[[x=>x<20,10],[x=>x<=40,50],[x=>x<=60,100],[x=>x<=80,150],[()=>true,200]])}export function calculateWR5(v:GreenMetricValues){return percent(v,"WR5","greenmetric.wr.treatedWaterConsumptionRatio",200,[[x=>x<=0,0],[x=>x<=25,50],[x=>x<=50,100],[x=>x<=75,150],[()=>true,200]])}export const calculateWR6=(v:GreenMetricValues)=>lv(v,"WR6","greenmetric.wr.waterPollutionControlLevel",200,[10,50,100,150,200]);
export function calculateTR1(v:GreenMetricValues){const ids=["greenmetric.tr.universityManagedCombustionCars","greenmetric.tr.dailyIncomingCombustionCars","greenmetric.tr.dailyIncomingCombustionMotorcycles",...GREEN_METRIC_POPULATION_METRIC_IDS];return derivedResult(v,"TR1","greenmetric.derived.combustionVehicleRatio",200,ids,[[x=>x>=1,0],[x=>x>.5,50],[x=>x>.125,100],[x=>x>=.045,150],[()=>true,200]])}
export const calculateTR2=(v:GreenMetricValues)=>lv(v,"TR2","greenmetric.tr.shuttleServiceLevel",250,[0,62.5,125,187.5,250]);export const calculateTR3=(v:GreenMetricValues)=>lv(v,"TR3","greenmetric.tr.zevAvailabilityLevel",200,[0,50,100,150,200]);
export function calculateTR4(v:GreenMetricValues){const ids=["greenmetric.tr.averageDailyZevCount",...GREEN_METRIC_POPULATION_METRIC_IDS];return derivedResult(v,"TR4","greenmetric.derived.zevPerCampusPopulation",200,ids,[[x=>x<=.002,10],[x=>x<=.004,50],[x=>x<=.008,100],[x=>x<=.02,150],[()=>true,200]])}
export function calculateTR5(v:GreenMetricValues){const ids=["greenmetric.common.groundParkingAreaM2","greenmetric.common.totalCampusAreaM2"],x=calculateDerivedValue("greenmetric.derived.parkingAreaRatio",v),warnings=getGreenMetricRelationWarningsForMetrics(v,ids),manual=x!=null&&nearlyEqual(x,1);return result("TR5",200,x,manual?null:bands(x,[[x=>x>11,0],[x=>x>7,50],[x=>x>4,100],[x=>x>1,150],[()=>true,200]]),ids,manual,warnings)}
export const calculateTR6=(v:GreenMetricValues)=>lv(v,"TR6","greenmetric.tr.parkingReductionProgramLevel",200,[0,50,100,150,200]);export const calculateTR7=(v:GreenMetricValues)=>count(v,"TR7","greenmetric.tr.privateVehicleReductionInitiativeCount",200,[0,1,2,3],[0,50,100,150,200]);export const calculateTR8=(v:GreenMetricValues)=>lv(v,"TR8","greenmetric.tr.pedestrianPathLevel",250,[0,62.5,125,187.5,250]);
const ratioIndicator=(v:GreenMetricValues,code:UiGreenMetricIndicatorCode,derivedId:string,a:string,b:string,max:number,bs:[(x:number)=>boolean,number][])=>derivedResult(v,code,derivedId,max,[a,b],bs);
export const calculateED1=(v:GreenMetricValues)=>ratioIndicator(v,"ED1","greenmetric.derived.sustainabilityCourseRatio","greenmetric.common.sustainabilityCourseCount","greenmetric.common.totalCourseCount",200,[[x=>x<=1,10],[x=>x<=5,50],[x=>x<=10,100],[x=>x<=20,150],[()=>true,200]]);export const calculateED2=(v:GreenMetricValues)=>ratioIndicator(v,"ED2","greenmetric.derived.sustainabilityResearchFundingRatio","greenmetric.common.sustainabilityResearchFundingUsd","greenmetric.common.totalResearchFundingUsd",200,[[x=>x<=1,10],[x=>x<=10,50],[x=>x<=20,100],[x=>x<=40,150],[()=>true,200]]);
export function calculateED3(v:GreenMetricValues){const ids=["greenmetric.common.sustainabilityPublicationCount","greenmetric.common.lecturerResearcherCount"];return derivedResult(v,"ED3","greenmetric.derived.sustainabilityPublicationsPerResearcher",200,ids,[[x=>x<.5,0],[x=>x<=1,50],[x=>x<=2,100],[x=>x<=3,150],[()=>true,200]])}
export const calculateED4=(v:GreenMetricValues)=>count(v,"ED4","greenmetric.ed.sustainabilityEventCount",100,[0,5,20,50],[0,25,50,75,100]);export const calculateED5=(v:GreenMetricValues)=>count(v,"ED5","greenmetric.ed.studentOrganizationActivityCount",150,[0,5,10,20],[0,37.5,75,112.5,150]);export const calculateED6=(v:GreenMetricValues)=>count(v,"ED6","greenmetric.ed.culturalActivityCount",100,[0,3,6,10],[0,25,50,75,100]);export const calculateED7=(v:GreenMetricValues)=>count(v,"ED7","greenmetric.ed.internationalCollaborationProgramCount",100,[0,3,6,10],[0,25,50,75,100]);export const calculateED8=(v:GreenMetricValues)=>count(v,"ED8","greenmetric.ed.studentCommunityServiceProjectCount",100,[0,3,6,10],[0,25,50,75,100]);export const calculateED9=(v:GreenMetricValues)=>count(v,"ED9","greenmetric.ed.sustainabilityStartupCount",100,[0,5,10,15],[0,25,50,75,100]);export const calculateED10=(v:GreenMetricValues)=>ratioIndicator(v,"ED10","greenmetric.derived.greenJobGraduateRatio","greenmetric.ed.greenJobGraduateCount","greenmetric.ed.totalGraduateCountLastThreeYears",50,[[x=>x<=1,2.5],[x=>x<=5,12.5],[x=>x<=10,25],[x=>x<=20,37.5],[()=>true,50]]);
export const calculateGD1=(v:GreenMetricValues)=>ratioIndicator(v,"GD1","greenmetric.derived.sustainabilityBudgetRatio","greenmetric.common.sustainabilityBudgetUsd","greenmetric.common.totalUniversityBudgetUsd",200,[[x=>x<=1,10],[x=>x<=5,50],[x=>x<=10,100],[x=>x<=15,150],[()=>true,200]]);
export const calculateGD2=(v:GreenMetricValues)=>lv(v,"GD2","greenmetric.gd.sustainabilityWebsiteStatus",200,[0,50,100,150,200]);export const calculateGD3=(v:GreenMetricValues)=>lv(v,"GD3","greenmetric.gd.sustainabilityReportStatus",100,[0,25,50,75,100]);export const calculateGD4=(v:GreenMetricValues)=>lv(v,"GD4","greenmetric.gd.financialReportStatus",100,[0,25,50,75,100]);export const calculateGD5=(v:GreenMetricValues)=>lv(v,"GD5","greenmetric.gd.sustainabilityOfficeStatus",100,[0,25,50,75,100]);export const calculateGD6=(v:GreenMetricValues)=>lv(v,"GD6","greenmetric.gd.ictSustainabilityLevel",50,[0,12.5,25,37.5,50]);export const calculateGD7=(v:GreenMetricValues)=>lv(v,"GD7","greenmetric.gd.advancedDigitalTechnologyPolicyLevel",50,[0,12.5,25,37.5,50]);export const calculateGD8=(v:GreenMetricValues)=>ratioIndicator(v,"GD8","greenmetric.derived.femaleLeaderRatio","greenmetric.common.femaleInstitutionalLeaderCount","greenmetric.common.totalInstitutionalLeaderCount",100,[[x=>x<=5,0],[x=>x<=20,25],[x=>x<=35,50],[x=>x<=50,75],[()=>true,100]]);export const calculateGD9=(v:GreenMetricValues)=>lv(v,"GD9","greenmetric.gd.antiCorruptionIntegrityLevel",50,[0,12.5,25,37.5,50]);export const calculateGD10=(v:GreenMetricValues)=>lv(v,"GD10","greenmetric.gd.whistleblowingComplaintLevel",50,[0,12.5,25,37.5,50]);export const calculateGD11=(v:GreenMetricValues)=>lv(v,"GD11","greenmetric.gd.lmsDigitalLiteracyLevel",50,[0,12.5,25,37.5,50]);export const calculateGD12=(v:GreenMetricValues)=>lv(v,"GD12","greenmetric.gd.codeOfEthicsLevel",50,[0,12.5,25,37.5,50]);
