import { optionList, renewableEnergyOptions } from "./greenmetric.options";
import { greenMetricCategoryMeta } from "./greenmetric.categories";
import type { GreenMetricCategoryCode, GreenMetricIndicatorDefinition, GreenMetricMetricDefinition, GreenMetricOption } from "@/src/types/greenmetric";

type MetricExtras = Partial<GreenMetricMetricDefinition>;
const num = (id: string, label: string, unit: string, extras: MetricExtras = {}): GreenMetricMetricDefinition => ({ id, label, inputType: extras.inputType ?? "number-range", min: extras.min ?? 0, step: extras.step ?? (unit === "USD" ? 1000 : 1), unit, required: !extras.infoOnly, fallbackMax: extras.fallbackMax ?? (extras.inputType === "percentage" ? 100 : 1000), integerOnly: extras.integerOnly ?? ((extras.step ?? (unit === "USD" ? 1000 : 1)) >= 1), ...extras });
const select = (id: string, label: string, options: GreenMetricOption[], extras: MetricExtras = {}): GreenMetricMetricDefinition => ({ id, label, inputType: "select", options, required: !extras.infoOnly, ...extras });
const derived = (id: string, label: string, unit: string, derivedFrom: string[], formulaLabel: string): GreenMetricMetricDefinition => ({ id, label, inputType: "readonly", readonly: true, unit, derivedFrom, formulaLabel });
const indicator = (categoryCode: GreenMetricCategoryCode, number: number, title: string, maxScore: number, metrics: GreenMetricMetricDefinition[], basic = metrics.some((item) => item.basic)): GreenMetricIndicatorDefinition => ({ id: `${categoryCode.toLowerCase()}-${number}`, code: `${categoryCode}${number}`, categoryCode, title, maxScore, metrics, basic, evidenceRequired: true });

const totalCampus = num("greenmetric.common.totalCampusAreaM2", "Toplam Kampüs Alanı", "m²", { min: 1, step: 100, shared: true, basic: true });
const buildingGround = num("greenmetric.common.buildingGroundFloorAreaM2", "Binaların Toplam Zemin Oturum Alanı", "m²", { step: 100, shared: true, basic: true });
const totalFloors = num("greenmetric.common.totalBuildingFloorAreaM2", "Tüm Binaların Toplam Kat Alanı", "m²", { step: 100, shared: true });
const regularStudents = num("greenmetric.common.regularStudentCount", "Düzenli Öğrenci Sayısı", "öğrenci", { step: 10, shared: true, basic: true });
const academicStaff = num("greenmetric.common.academicStaffCount", "Akademik Personel Sayısı", "personel", { shared: true, basic: true });
const administrativeStaff = num("greenmetric.common.administrativeStaffCount", "İdari Personel Sayısı", "personel", { shared: true, basic: true });
const campusPopulation = derived("greenmetric.derived.campusPopulation", "Toplam Kampüs Nüfusu", "kişi", [regularStudents.id, academicStaff.id, administrativeStaff.id], "Düzenli öğrenci + akademik personel + idari personel");

export const greenMetricContextMetrics: GreenMetricMetricDefinition[] = [
  totalCampus, buildingGround, totalFloors, regularStudents,
  academicStaff, administrativeStaff, campusPopulation,
];

const level = (...labels: string[]) => optionList(...labels);
const program5 = level("Program yok", "Program hazırlık aşamasında", "%1–50 uygulanıyor", "%50–75 uygulanıyor", "%75’ten fazla uygulanıyor");
const renewableProduction = renewableEnergyOptions.map((option) => num(`greenmetric.ec.renewableProduction.${option.value}Kwh`, `${option.label} Yıllık Üretimi`, "kWh", { step: 1000, infoOnly: true }));

export const greenMetricIndicators: GreenMetricIndicatorDefinition[] = [
  indicator("SI", 1, "Açık Alanın Toplam Kampüs Alanına Oranı", 200, [totalCampus, buildingGround, derived("greenmetric.derived.openSpaceAreaM2", "Açık Alan", "m²", [totalCampus.id, buildingGround.id], "Toplam kampüs alanı − bina zemin oturum alanı"), derived("greenmetric.derived.openSpaceRatio", "Açık Alan Oranı", "%", [totalCampus.id, buildingGround.id], "Açık alan / toplam kampüs alanı × 100")], true),
  indicator("SI", 2, "Akademik veya Toplumsal Amaçla Kullanılan Ormanlık Alan", 100, [num("greenmetric.si.forestVegetationAreaM2", "Ormanlık Alan", "m²", { step: 100, basic: true }), totalCampus, derived("greenmetric.derived.forestVegetationRatio", "Ormanlık Alan Oranı", "%", ["greenmetric.si.forestVegetationAreaM2", totalCampus.id], "Ormanlık alan / toplam kampüs alanı × 100")]),
  indicator("SI", 3, "Bitkilendirilmiş Alan", 200, [num("greenmetric.si.plantedVegetationAreaM2", "Bitkilendirilmiş Alan", "m²", { step: 100, basic: true, description: "Ormanlık alanı bu değere tekrar dahil etmeyin." }), totalCampus, derived("greenmetric.derived.plantedVegetationRatio", "Bitkilendirilmiş Alan Oranı", "%", ["greenmetric.si.plantedVegetationAreaM2", totalCampus.id], "Bitkilendirilmiş alan / toplam kampüs alanı × 100")]),
  indicator("SI", 4, "Kampüs Nüfusu Başına Açık Alan", 200, [totalCampus, buildingGround, regularStudents, academicStaff, administrativeStaff, derived("greenmetric.derived.openSpacePerPerson", "Kişi Başına Açık Alan", "m²/kişi", [totalCampus.id, buildingGround.id, regularStudents.id, academicStaff.id, administrativeStaff.id], "Açık alan / toplam kampüs nüfusu")]),
  indicator("SI", 5, "Engelli, Özel Gereksinimli ve Doğum/Bakım İhtiyaçlarına Yönelik Tesisler", 100, [select("greenmetric.si.accessibilityFacilitiesLevel", "Erişilebilirlik Tesisleri Düzeyi", level("Tesis veya politika bulunmuyor", "Politika mevcut", "Tesisler planlama aşamasında", "Tesisler kısmen mevcut ve çalışıyor", "Tesisler tüm binalarda mevcut ve tam olarak çalışıyor"), { basic: true })]),
  indicator("SI", 6, "Güvenlik ve Emniyet Tesisleri", 100, [select("greenmetric.si.securitySafetyLevel", "Güvenlik ve Emniyet Düzeyi", level("Yalnızca pasif güvenlik sistemi", "CCTV ve acil yardım hattı/butonu mevcut ve çalışıyor", "CCTV, acil yardım sistemi, sertifikalı personel, yangın söndürücü ve hidrant mevcut", "Sistem tam çalışıyor; olaylara müdahale süresi 5 dakikadan fazla", "Sistem tam çalışıyor; olaylara müdahale süresi 5 dakikadan az"))]),
  indicator("SI", 7, "Öğrenci ve Personel Sağlığını Destekleyen Altyapı", 100, [select("greenmetric.si.healthInfrastructureLevel", "Sağlık Altyapısı Düzeyi", level("İlk yardım altyapısı bulunmuyor", "İlk yardım, acil oda, klinik ve personel mevcut", "İlk yardım, acil oda, klinik ve sertifikalı personel mevcut", "Hastane dahil kapsamlı sağlık altyapısı mevcut", "Sistemli sağlık altyapısı mevcut ve kamu erişimine açık"), { basic: true })]),
  indicator("SI", 8, "Flora, Fauna, Yaban Hayatı ve Genetik Kaynakların Korunması", 100, [select("greenmetric.si.conservationProgramLevel", "Koruma Programı Düzeyi", level("Koruma programı hazırlık aşamasında", "Program %1–25 uygulanıyor", "Program %25–50 uygulanıyor", "Program %50–75 uygulanıyor", "Program %75’ten fazla uygulanıyor"))]),

  indicator("EC", 1, "Enerji Verimli Cihazların Kullanımı", 200, [num("greenmetric.ec.energyEfficientApplianceRatio", "Enerji Verimli Cihaz Oranı", "%", { inputType: "percentage", max: 100, step: 0.1, basic: true })]),
  indicator("EC", 2, "Akıllı Bina Uygulaması", 300, [num("greenmetric.ec.smartBuildingAreaM2", "Akıllı Binaların Toplam Kat Alanı", "m²", { step: 100, basic: true }), totalFloors, derived("greenmetric.derived.smartBuildingRatio", "Akıllı Bina Oranı", "%", ["greenmetric.ec.smartBuildingAreaM2", totalFloors.id], "Akıllı bina alanı / toplam bina kat alanı × 100")]),
  indicator("EC", 3, "Kampüsteki Yenilenebilir Enerji Kaynağı Sayısı", 300, [{ id: "greenmetric.ec.renewableEnergySources", label: "Yenilenebilir Enerji Kaynakları", inputType: "multi-select", options: renewableEnergyOptions, required: true, basic: true }, ...renewableProduction, derived("greenmetric.derived.renewableEnergySourceCount", "Seçilen Kaynak Sayısı", "kaynak", ["greenmetric.ec.renewableEnergySources"], "Seçilen yenilenebilir enerji kaynaklarının sayısı"), derived("greenmetric.derived.totalRenewableEnergyProductionKwh", "Toplam Yenilenebilir Enerji Üretimi", "kWh", renewableProduction.map((item) => item.id), "Kaynak bazlı yıllık üretimlerin toplamı")]),
  indicator("EC", 4, "Kampüs Nüfusu Başına Elektrik Tüketimi", 200, [num("greenmetric.common.totalAnnualElectricityKwh", "Yıllık Toplam Elektrik Tüketimi", "kWh", { step: 1000, fallbackMax: 1250, shared: true, basic: true }), regularStudents, academicStaff, administrativeStaff, derived("greenmetric.derived.electricityPerPerson", "Kişi Başına Elektrik Tüketimi", "kWh/kişi", ["greenmetric.common.totalAnnualElectricityKwh", regularStudents.id, academicStaff.id, administrativeStaff.id], "Yıllık elektrik tüketimi / kampüs nüfusu")]),
  indicator("EC", 5, "Yenilenebilir Enerji Üretiminin Toplam Enerji Kullanımına Oranı", 200, [num("greenmetric.common.totalAnnualEnergyUsageKwh", "Yıllık Toplam Enerji Kullanımı", "kWh", { step: 1000, shared: true, basic: true }), ...renewableProduction, derived("greenmetric.derived.renewableEnergyRatio", "Yenilenebilir Enerji Oranı", "%", ["greenmetric.common.totalAnnualEnergyUsageKwh", ...renewableProduction.map((item) => item.id)], "Toplam yenilenebilir enerji üretimi / toplam enerji kullanımı × 100")]),
  indicator("EC", 6, "Binalarda Uygulanan Yeşil Bina Unsurları", 200, [num("greenmetric.ec.greenBuildingElementCount", "Yeşil Bina Unsuru Sayısı", "unsur", { description: "Doğal havalandırma, doğal aydınlatma, enerji yöneticisi ve sertifikalı yeşil bina örnekleri dahildir." })]),
  indicator("EC", 7, "Sera Gazı Emisyonlarını Azaltma Programı", 200, [select("greenmetric.ec.ghgReductionProgramLevel", "Sera Gazı Azaltma Programı", level("Program yok", "Program hazırlık aşamasında", "Program bir emisyon kapsamını ele alıyor", "Program iki emisyon kapsamını ele alıyor", "Program Kapsam 1, 2 ve 3’ün tamamını ele alıyor"), { basic: true })]),
  indicator("EC", 8, "Kampüs Nüfusu Başına Karbon Ayak İzi", 200, [num("greenmetric.common.totalCarbonFootprintTons", "Son 12 Aylık Toplam Karbon Ayak İzi", "ton CO₂e", { step: 0.01, shared: true, basic: true, warning: "Uçuş emisyonları 2026 soru tanımında hariç tutulur." }), regularStudents, academicStaff, administrativeStaff, derived("greenmetric.derived.carbonFootprintPerPerson", "Kişi Başına Karbon Ayak İzi", "ton CO₂e/kişi", ["greenmetric.common.totalCarbonFootprintTons", regularStudents.id, academicStaff.id, administrativeStaff.id], "Toplam karbon ayak izi / kampüs nüfusu")]),
  indicator("EC", 9, "Enerji ve İklim Değişikliği Alanındaki Yenilikçi Program Sayısı", 100, [num("greenmetric.ec.innovativeProgramCount", "Yenilikçi Program Sayısı", "program", { description: "Satın alınan hazır teknolojiler üniversite tarafından geliştirilmiş yenilik sayılmaz." })]),
  indicator("EC", 10, "İklim Değişikliği Konusunda Etkili Üniversite Programları", 100, [select("greenmetric.ec.climateImpactProgramLevel", "İklim Etki Programı Düzeyi", level("Program yok", "Program hazırlık aşamasında", "Yerel topluluklara yönelik uygulama", "Ulusal düzeyde uygulama", "Uluslararası düzeyde uygulama"), { basic: true })]),

  indicator("WS", 1, "Üniversite Atıkları İçin 3R Programı", 200, [select("greenmetric.ws.threeRProgramLevel", "3R Programı Düzeyi", program5, { basic: true })]),
  indicator("WS", 2, "Kâğıt ve Plastik Kullanımını Azaltma Programı", 300, [num("greenmetric.ws.paperPlasticReductionProgramCount", "Kâğıt ve Plastik Azaltma Programı Sayısı", "program", { basic: true })]),
  indicator("WS", 3, "Organik Atıkların İşlenmesi", 300, [num("greenmetric.ws.organicWasteProducedCurrentTons", "Üretilen Organik Atık — Mevcut Yıl", "ton", { step: 0.01 }), num("greenmetric.ws.organicWasteTreatedCurrentTons", "İşlenen Organik Atık", "ton", { step: 0.01 }), derived("greenmetric.derived.organicWasteTreatmentRatio", "Organik Atık İşleme Oranı", "%", ["greenmetric.ws.organicWasteTreatedCurrentTons", "greenmetric.ws.organicWasteProducedCurrentTons"], "İşlenen / üretilen organik atık × 100")]),
  indicator("WS", 4, "İnorganik Atıkların İşlenmesi", 300, [num("greenmetric.ws.inorganicWasteProducedCurrentTons", "Üretilen İnorganik Atık — Mevcut Yıl", "ton", { step: 0.01 }), num("greenmetric.ws.inorganicWasteTreatedCurrentTons", "İşlenen İnorganik Atık", "ton", { step: 0.01 }), derived("greenmetric.derived.inorganicWasteTreatmentRatio", "İnorganik Atık İşleme Oranı", "%", ["greenmetric.ws.inorganicWasteTreatedCurrentTons", "greenmetric.ws.inorganicWasteProducedCurrentTons"], "İşlenen / üretilen inorganik atık × 100")]),
  indicator("WS", 5, "Toksik ve Tehlikeli Atıkların İşlenmesi", 300, [num("greenmetric.ws.toxicWasteProducedCurrentTons", "Üretilen Toksik Atık — Mevcut Yıl", "ton", { step: 0.01 }), num("greenmetric.ws.toxicWasteTreatedCurrentTons", "İşlenen Toksik Atık", "ton", { step: 0.01 }), derived("greenmetric.derived.toxicWasteTreatmentRatio", "Toksik Atık İşleme Oranı", "%", ["greenmetric.ws.toxicWasteTreatedCurrentTons", "greenmetric.ws.toxicWasteProducedCurrentTons"], "İşlenen / üretilen toksik atık × 100")]),
  indicator("WS", 6, "Atık Su Bertarafı", 300, [select("greenmetric.ws.sewageTreatmentLevel", "Atık Su Arıtma Düzeyi", level("Arıtılmadan su yollarına deşarj", "Ön arıtma", "Birincil arıtma", "İkincil arıtma", "Üçüncül/ileri arıtma"), { basic: true })]),

  indicator("WR", 1, "Orman ve Bitkilendirilmiş Alanlar Dışındaki Su Emilim Alanı", 100, [num("greenmetric.wr.waterAbsorptionAreaM2", "Su Emilim Alanı", "m²", { step: 100, description: "Orman ve bitkilendirilmiş alanları bu alana tekrar dahil etmeyin." }), totalCampus, derived("greenmetric.derived.waterAbsorptionRatio", "Su Emilim Alanı Oranı", "%", ["greenmetric.wr.waterAbsorptionAreaM2", totalCampus.id], "Su emilim alanı / toplam kampüs alanı × 100")]),
  indicator("WR", 2, "Su Tasarrufu Programı ve Uygulanması", 200, [select("greenmetric.wr.waterConservationLevel", "Su Tasarrufu Düzeyi", level("Program yok", "Program hazırlık aşamasında", "Suyun %1–25’i korunuyor", "Suyun %25–50’si korunuyor", "Suyun %50’den fazlası korunuyor"), { basic: true })]),
  indicator("WR", 3, "Su Geri Dönüşüm Programının Uygulanması", 200, [select("greenmetric.wr.waterRecyclingLevel", "Su Geri Dönüşüm Düzeyi", level("Program yok", "Program hazırlık aşamasında", "Suyun %1–25’i geri dönüştürülüyor", "Suyun %25–50’si geri dönüştürülüyor", "Suyun %50’den fazlası geri dönüştürülüyor"), { basic: true })]),
  indicator("WR", 4, "Su Tasarruflu Cihazların Kullanımı", 200, [num("greenmetric.wr.waterEfficientApplianceRatio", "Su Tasarruflu Cihaz Oranı", "%", { inputType: "percentage", max: 100, step: 0.1, basic: true })]),
  indicator("WR", 5, "Arıtılmış Su Tüketimi", 200, [num("greenmetric.wr.treatedWaterConsumptionRatio", "Arıtılmış Su Tüketim Oranı", "%", { inputType: "percentage", max: 100, step: 0.1, basic: true })]),
  indicator("WR", 6, "Kampüs Alanında Su Kirliliği Kontrolü", 200, [select("greenmetric.wr.waterPollutionControlLevel", "Su Kirliliği Kontrol Düzeyi", level("Politika ve program tasarım aşamasında", "Sistem yapım aşamasında", "Erken uygulama aşamasında", "Tam uygulanıyor ve zaman zaman izleniyor", "Tam uygulanıyor ve düzenli izleniyor"))]),

  indicator("TR", 1, "İçten Yanmalı Araçların Kampüs Nüfusuna Oranı", 200, [num("greenmetric.tr.universityManagedCombustionCars", "Üniversite Tarafından Yönetilen İçten Yanmalı Otomobil", "araç"), num("greenmetric.tr.dailyIncomingCombustionCars", "Günlük Gelen İçten Yanmalı Otomobil", "araç"), num("greenmetric.tr.dailyIncomingCombustionMotorcycles", "Günlük Gelen İçten Yanmalı Motosiklet", "araç"), regularStudents, academicStaff, administrativeStaff, derived("greenmetric.derived.combustionVehicleRatio", "İçten Yanmalı Araç / Kampüs Nüfusu", "araç/kişi", ["greenmetric.tr.universityManagedCombustionCars", "greenmetric.tr.dailyIncomingCombustionCars", "greenmetric.tr.dailyIncomingCombustionMotorcycles", regularStudents.id, academicStaff.id, administrativeStaff.id], "Toplam içten yanmalı araç / kampüs nüfusu")]),
  indicator("TR", 2, "Servis Hizmetleri", 250, [select("greenmetric.tr.shuttleServiceLevel", "Servis Hizmeti Düzeyi", level("Mümkün ancak üniversite tarafından sağlanmıyor", "Düzenli servis mevcut ancak ücretsiz değil", "Üniversite maliyetin bir kısmını karşılıyor", "Üniversite tarafından düzenli ve ücretsiz sağlanıyor", "Düzenli, ücretsiz ve sıfır emisyonlu servis sağlanıyor veya servis uygulanabilir değil"), { basic: true })]),
  indicator("TR", 3, "Kampüste Sıfır Emisyonlu Araç Bulunması", 200, [select("greenmetric.tr.zevAvailabilityLevel", "Sıfır Emisyonlu Araç Düzeyi", level("Sıfır emisyonlu araç bulunmuyor", "Kullanım mümkün veya uygulanabilir değil", "Araçlar mevcut ancak üniversite tarafından sağlanmıyor", "Üniversite tarafından ücretli olarak sağlanıyor", "Üniversite tarafından ücretsiz sağlanıyor"), { basic: true })]),
  indicator("TR", 4, "Sıfır Emisyonlu Araçların Kampüs Nüfusuna Oranı", 200, [num("greenmetric.tr.averageDailyZevCount", "Günlük Ortalama Sıfır Emisyonlu Araç", "araç", { basic: true }), regularStudents, academicStaff, administrativeStaff, derived("greenmetric.derived.zevPerCampusPopulation", "Sıfır Emisyonlu Araç / Kampüs Nüfusu", "araç/kişi", ["greenmetric.tr.averageDailyZevCount", regularStudents.id, academicStaff.id, administrativeStaff.id], "Günlük sıfır emisyonlu araç / kampüs nüfusu")]),
  indicator("TR", 5, "Otopark Alanının Toplam Kampüs Alanına Oranı", 200, [num("greenmetric.common.groundParkingAreaM2", "Zemin Otopark Alanı", "m²", { step: 100, shared: true, basic: true, warning: "Bu gösterge ters yönlüdür; düşük oran daha iyi performans anlamına gelir." }), totalCampus, derived("greenmetric.derived.parkingAreaRatio", "Otopark Alanı Oranı", "%", ["greenmetric.common.groundParkingAreaM2", totalCampus.id], "Zemin otopark alanı / toplam kampüs alanı × 100")]),
  indicator("TR", 6, "Son Üç Yılda Otopark Alanını Sınırlandırma veya Azaltma Programı", 200, [select("greenmetric.tr.parkingReductionProgramLevel", "Otopark Azaltma Programı", level("Program yok", "Hazırlık aşamasında", "Otopark alanı %10’dan az azaltıldı", "Otopark alanı %10–30 azaltıldı", "Otopark alanı %30’dan fazla azaltıldı veya pratik azaltma sınırına ulaşıldı"))]),
  indicator("TR", 7, "Kampüsteki Özel Araç Kullanımını Azaltmaya Yönelik Girişimler", 200, [num("greenmetric.tr.privateVehicleReductionInitiativeCount", "Özel Araç Azaltma Girişimi Sayısı", "girişim", { basic: true })]),
  indicator("TR", 8, "Kampüsteki Yaya Yolları", 250, [select("greenmetric.tr.pedestrianPathLevel", "Yaya Yolu Düzeyi", level("Yaya yolu yok", "Yaya yolu mevcut", "Mevcut ve güvenlik için tasarlanmış", "Güvenlik ve konfor için tasarlanmış", "Güvenlik, konfor ve engelli erişimi için tasarlanmış"), { basic: true })]),

  indicator("ED", 1, "Sürdürülebilirlik Derslerinin Toplam Derslere Oranı", 200, [num("greenmetric.common.sustainabilityCourseCount", "Sürdürülebilirlik Dersi Sayısı", "ders", { shared: true }), num("greenmetric.common.totalCourseCount", "Toplam Ders Sayısı", "ders", { shared: true }), derived("greenmetric.derived.sustainabilityCourseRatio", "Sürdürülebilirlik Dersi Oranı", "%", ["greenmetric.common.sustainabilityCourseCount", "greenmetric.common.totalCourseCount"], "Sürdürülebilirlik dersleri / toplam dersler × 100")]),
  indicator("ED", 2, "Sürdürülebilirlik Araştırma Fonunun Toplam Araştırma Fonuna Oranı", 200, [num("greenmetric.common.sustainabilityResearchFundingUsd", "Sürdürülebilirlik Araştırma Fonu", "USD", { shared: true, description: "Son üç yılın yıllık ortalamasını girin." }), num("greenmetric.common.totalResearchFundingUsd", "Toplam Araştırma Fonu", "USD", { shared: true, description: "Son üç yılın yıllık ortalamasını girin." }), derived("greenmetric.derived.sustainabilityResearchFundingRatio", "Sürdürülebilirlik Araştırma Fonu Oranı", "%", ["greenmetric.common.sustainabilityResearchFundingUsd", "greenmetric.common.totalResearchFundingUsd"], "Sürdürülebilirlik araştırma fonu / toplam araştırma fonu × 100")]),
  indicator("ED", 3, "Sürdürülebilirlik Yayınlarının Akademisyen ve Araştırmacılara Oranı", 200, [num("greenmetric.common.lecturerResearcherCount", "Akademisyen ve Araştırmacı Sayısı", "kişi", { shared: true }), num("greenmetric.common.sustainabilityPublicationCount", "Sürdürülebilirlik Yayını Sayısı", "yayın", { shared: true }), derived("greenmetric.derived.sustainabilityPublicationsPerResearcher", "Araştırmacı Başına Sürdürülebilirlik Yayını", "yayın/kişi", ["greenmetric.common.sustainabilityPublicationCount", "greenmetric.common.lecturerResearcherCount"], "Sürdürülebilirlik yayını / akademisyen ve araştırmacı")]),
  indicator("ED", 4, "Sürdürülebilirlikle İlgili Etkinlik veya Program Sayısı", 100, [num("greenmetric.ed.sustainabilityEventCount", "Sürdürülebilirlik Etkinliği Sayısı", "etkinlik", { basic: true, description: "Son üç yılın yıllık ortalamasını girin." })]),
  indicator("ED", 5, "Öğrenci Topluluklarının Düzenlediği Sürdürülebilirlik Faaliyetleri", 150, [num("greenmetric.ed.studentOrganizationActivityCount", "Öğrenci Topluluğu Sürdürülebilirlik Faaliyeti", "faaliyet/yıl")]),
  indicator("ED", 6, "Kampüste Düzenlenen Kültürel Faaliyet Sayısı", 100, [num("greenmetric.ed.culturalActivityCount", "Kültürel Faaliyet Sayısı", "etkinlik/yıl")]),
  indicator("ED", 7, "Uluslararası İş Birlikli Sürdürülebilirlik Programları", 100, [num("greenmetric.ed.internationalCollaborationProgramCount", "Uluslararası İş Birlikli Program Sayısı", "program/yıl")]),
  indicator("ED", 8, "Öğrencilerin Katıldığı Sürdürülebilirlik Temalı Toplumsal Hizmetler", 100, [num("greenmetric.ed.studentCommunityServiceProjectCount", "Toplumsal Hizmet Projesi Sayısı", "proje/yıl")]),
  indicator("ED", 9, "Sürdürülebilirlikle İlgili Girişim/Start-up Sayısı", 100, [num("greenmetric.ed.sustainabilityStartupCount", "Sürdürülebilirlik Girişimi Sayısı", "girişim", { description: "Yalnızca son üç yılda kurulan girişimleri sayın." })]),
  indicator("ED", 10, "Son Üç Yılda Yeşil İşlerde Çalışan Mezunların Oranı", 50, [num("greenmetric.ed.greenJobGraduateCount", "Yeşil İşlerde Çalışan Mezun Sayısı", "mezun"), num("greenmetric.ed.totalGraduateCountLastThreeYears", "Son Üç Yıldaki Toplam Mezun Sayısı", "mezun"), derived("greenmetric.derived.greenJobGraduateRatio", "Yeşil İşlerde Çalışan Mezun Oranı", "%", ["greenmetric.ed.greenJobGraduateCount", "greenmetric.ed.totalGraduateCountLastThreeYears"], "Yeşil işlerde çalışan mezun / toplam mezun × 100")]),

  indicator("GD", 1, "Sürdürülebilirlik Çalışmalarına Ayrılan Üniversite Bütçesi Oranı", 200, [num("greenmetric.common.totalUniversityBudgetUsd", "Toplam Üniversite Bütçesi", "USD", { shared: true, description: "Son üç yılın yıllık ortalamasını girin." }), num("greenmetric.common.sustainabilityBudgetUsd", "Sürdürülebilirlik Bütçesi", "USD", { shared: true, description: "Son üç yılın yıllık ortalamasını girin." }), derived("greenmetric.derived.sustainabilityBudgetRatio", "Sürdürülebilirlik Bütçesi Oranı", "%", ["greenmetric.common.sustainabilityBudgetUsd", "greenmetric.common.totalUniversityBudgetUsd"], "Sürdürülebilirlik bütçesi / toplam bütçe × 100")]),
  indicator("GD", 2, "Üniversite Tarafından İşletilen Sürdürülebilirlik Web Sitesi", 200, [select("greenmetric.gd.sustainabilityWebsiteStatus", "Sürdürülebilirlik Web Sitesi Durumu", level("Web sitesi bulunmuyor", "Hazırlanıyor veya yapım aşamasında", "Mevcut ve erişilebilir", "Mevcut, erişilebilir ve zaman zaman güncelleniyor", "Mevcut, erişilebilir ve düzenli güncelleniyor"), { basic: true })]),
  indicator("GD", 3, "Sürdürülebilirlik Raporu", 100, [select("greenmetric.gd.sustainabilityReportStatus", "Sürdürülebilirlik Raporu Durumu", level("Rapor bulunmuyor", "Hazırlık aşamasında", "Mevcut ancak kamuya açık değil", "Kamuya açık ve zaman zaman yayımlanıyor", "Kamuya açık ve yıllık yayımlanıyor"), { basic: true })]),
  indicator("GD", 4, "Mali Rapor", 100, [select("greenmetric.gd.financialReportStatus", "Mali Rapor Durumu", level("Rapor bulunmuyor", "Hazırlık aşamasında", "Mevcut ancak kamuya açık değil", "Kamuya açık ve zaman zaman yayımlanıyor", "Kamuya açık ve yıllık yayımlanıyor"))]),
  indicator("GD", 5, "Kampüs Sürdürülebilirliğini Koordine Eden Birim veya Ofis", 100, [select("greenmetric.gd.sustainabilityOfficeStatus", "Sürdürülebilirlik Ofisi Durumu", level("Geçici görev gücü veya komisyon", "Birim/ofis geliştirme aşamasında", "Resmî karar, yapı ve görev tanımı mevcut; erken aşamada", "Resmî birim/ofis çalışıyor", "Resmî birim/ofis çalışıyor ve üniversitenin sürdürülebilirlik uygulamalarını yönetiyor"), { basic: true })]),
  indicator("GD", 6, "Sürdürülebilirlik Programlarında Bilgi ve İletişim Teknolojilerinin Kullanımı", 50, [select("greenmetric.gd.ictSustainabilityLevel", "BİT Kullanım Düzeyi", level("Kullanım yok", "Planlama aşamasında", "Uygulanıyor", "Uygulanıyor ve değerlendiriliyor", "Uygulanıyor, değerlendiriliyor ve geliştiriliyor"), { basic: true })]),
  indicator("GD", 7, "Karar Verme ve Hizmet Sunumunda İleri Dijital Teknoloji Politikası", 50, [select("greenmetric.gd.advancedDigitalTechnologyPolicyLevel", "İleri Dijital Teknoloji Politikası", level("Politika yok", "Başlangıç düzeyinde ve sınırlı birimlerde", "Kısmi uygulama", "Birçok akademik ve idari işlevde geniş uygulama", "Kurum genelinde ileri ve bütünleşik uygulama"), { basic: true })]),
  indicator("GD", 8, "Kadın Yöneticilerin Toplam Yöneticilere Oranı", 100, [num("greenmetric.common.totalInstitutionalLeaderCount", "Toplam Kurumsal Yönetici Sayısı", "yönetici", { shared: true }), num("greenmetric.common.femaleInstitutionalLeaderCount", "Kadın Kurumsal Yönetici Sayısı", "yönetici", { shared: true }), derived("greenmetric.derived.femaleLeaderRatio", "Kadın Yönetici Oranı", "%", ["greenmetric.common.femaleInstitutionalLeaderCount", "greenmetric.common.totalInstitutionalLeaderCount"], "Kadın yönetici / toplam yönetici × 100")]),
  indicator("GD", 9, "Yolsuzlukla Mücadele ve Kurumsal Dürüstlük Sistemi", 50, [select("greenmetric.gd.antiCorruptionIntegrityLevel", "Yolsuzlukla Mücadele Sistemi", level("Sistem yok", "Planlama aşamasında", "Uygulandı", "Uygulandı ve değerlendirildi", "Uygulandı, değerlendirildi ve geliştiriliyor"))]),
  indicator("GD", 10, "İhbar ve Şikâyet Sistemi", 50, [select("greenmetric.gd.whistleblowingComplaintLevel", "İhbar ve Şikâyet Sistemi", level("Sistem yok", "Planlama aşamasında", "Uygulandı", "Uygulandı ve değerlendirildi", "Uygulandı, değerlendirildi ve geliştiriliyor"), { basic: true })]),
  indicator("GD", 11, "LMS Destekli Dijital Okuryazarlık Programı", 50, [select("greenmetric.gd.lmsDigitalLiteracyLevel", "LMS Destekli Dijital Okuryazarlık Düzeyi", level("Program yok", "Planlama aşamasında", "Uygulandı", "Uygulandı ve değerlendirildi", "Uygulandı, değerlendirildi ve geliştiriliyor"))]),
  indicator("GD", 12, "Yönetici, Akademik Personel, İdari Personel ve Öğrenciler İçin Yazılı Etik Kuralları", 50, [select("greenmetric.gd.codeOfEthicsLevel", "Yazılı Etik Kuralları Düzeyi", level("Yazılı etik kuralı yok", "Taslak veya hazırlık aşamasında", "Resmî olarak var ancak yalnız belirli grupları kapsıyor veya tutarlı uygulanmıyor", "Tüm grupları kapsıyor, uygulanıyor ve izleniyor", "Tüm grupları kapsıyor, tam uygulanıyor, düzenli inceleniyor ve aktif biçimde yürütülüyor"), { basic: true })]),
];

export const expectedCounts = { SI: 8, EC: 10, WS: 6, WR: 6, TR: 8, ED: 10, GD: 12 } as const;
const expectedScores = { SI: 1100, EC: 2000, WS: 1700, WR: 1100, TR: 1700, ED: 1300, GD: 1100 } as const;

for (const category of greenMetricCategoryMeta) {
  const actual = greenMetricIndicators.filter((item) => item.categoryCode === category.code);
  const actualScore = actual.reduce((total, item) => total + item.maxScore, 0);
  if (actual.length !== expectedCounts[category.code]) throw new Error(`${category.code} gösterge sayısı ${expectedCounts[category.code]} olmalıdır. Mevcut: ${actual.length}`);
  if (actualScore !== expectedScores[category.code]) throw new Error(`${category.code} azami puanı ${expectedScores[category.code]} olmalıdır. Mevcut: ${actualScore}`);
}
if (greenMetricIndicators.length !== 60) throw new Error(`UI GreenMetric gösterge sayısı 60 olmalıdır. Mevcut: ${greenMetricIndicators.length}`);
