import {theCategories,theInitialValues} from "@/src/config/the.metrics";import {THE_ACTIVE_DATA_MODE} from "@/src/config/the.data-mode";import {THE_MODEL_BASELINE_ASSUMPTIONS} from "@/src/config/the.public-simulation";import {qsCategories,qsInitialValues} from "@/src/config/qs.metrics";import {QS_ACTIVE_DATA_MODE} from "@/src/config/qs.data-mode";import {QS_PUBLIC_SIMULATION_BASELINE_VALUES} from "@/src/config/qs.public-simulation";import {greenMetricCategories} from "@/src/config/greenmetric.categories";import {greenMetricContextMetrics,greenMetricIndicators} from "@/src/config/greenmetric.metrics";import {greenMetricEmptyValues} from "@/src/data/greenmetric.baseline";import type {BaselineRecord,MethodologyId} from "@/src/contexts/MethodologyBaselineContext";import type {GreenMetricValue} from "@/src/types/greenmetric";
export interface RegistryMetric{id:string;label:string;description?:string;inputType:string;min?:number;max?:number;step?:number;unit?:string;options?:{value:string;label:string}[];required?:boolean}export interface RegistryGroup{id:string;title:string;metrics:RegistryMetric[]}
const unique=(metrics:RegistryMetric[])=>Array.from(new Map(metrics.map(metric=>[metric.id,metric])).values());
const theGroups:RegistryGroup[]=theCategories.map(category=>({id:category.id,title:category.title,metrics:unique(category.metrics)}));
const qsGroups:RegistryGroup[]=qsCategories.map(category=>({id:category.id,title:category.title,metrics:unique(category.indicators.flatMap(indicator=>indicator.metrics))}));
const greenGroups:RegistryGroup[]=[{id:"context",title:"Ortak Kampüs Verileri",metrics:greenMetricContextMetrics.filter(metric=>!metric.readonly)},...greenMetricCategories.map(category=>({id:category.id,title:category.title,metrics:unique(greenMetricIndicators.filter(indicator=>indicator.categoryCode===category.code).flatMap(indicator=>indicator.metrics).filter(metric=>!metric.readonly))}))];
export const methodologyRegistry:Record<MethodologyId,{label:string;groups:RegistryGroup[];defaults:BaselineRecord}>={the:{label:"THE",groups:theGroups,defaults:THE_ACTIVE_DATA_MODE==="public-simulation"?THE_MODEL_BASELINE_ASSUMPTIONS:theInitialValues},qs:{label:"QS",groups:qsGroups,defaults:QS_ACTIVE_DATA_MODE==="public-simulation"?QS_PUBLIC_SIMULATION_BASELINE_VALUES:qsInitialValues},"ui-greenmetric":{label:"UI GreenMetric",groups:greenGroups,defaults:greenMetricEmptyValues}};
export function validateBaselineValues(methodology:MethodologyId,values:BaselineRecord){const metrics=new Map(methodologyRegistry[methodology].groups.flatMap(group=>group.metrics).map(metric=>[metric.id,metric]));const valid:BaselineRecord={};const errors:Record<string,string>={};for(const[id,value]of Object.entries(values)){const metric=metrics.get(id);if(!metric)continue;if(isValid(metric,value))valid[id]=value;else errors[id]="Geçersiz değer"}return{valid,errors}}
function isValid(metric:RegistryMetric,value:GreenMetricValue){if(value===null)return metric.required===false;if(metric.inputType==="select")return typeof value==="string"&&Boolean(metric.options?.some(option=>option.value===value));if(metric.inputType==="multi-select")return Array.isArray(value)&&value.every(item=>metric.options?.some(option=>option.value===item));if(metric.inputType==="url")return typeof value==="string";if(typeof value!=="number"||!Number.isFinite(value))return false;return (metric.min===undefined||value>=metric.min)&&(metric.max===undefined||value<=metric.max)}
export function createBaselineOverrides(methodology:MethodologyId,draft:BaselineRecord){const defaults=methodologyRegistry[methodology].defaults;return Object.fromEntries(Object.entries(draft).filter(([id,value])=>JSON.stringify(value)!==JSON.stringify(defaults[id]))) as BaselineRecord}
